on:
    push:
        branches:
        - main
    pull_request:
    release:
      types: [published]

jobs:
    build:
        name: Build ASCII Art Suite
        runs-on: ubuntu-latest
        steps:
        # initial checkout of this repo
        - uses: actions/checkout@v4
        - name: Sparse Checkout für Submodule
          run: |
            git submodule init
            git submodule update --depth 1 --checkout --remote
            cd generator/external/stb
            git sparse-checkout init --cone
            git sparse-checkout set --skip-checks stb_image.h
            git pull origin master
        - name: Shorten Image ref
          run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            version: v0.9.1 # Pin version to avoid Manifest parsing error in FluxCD
        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_PAT }}
        - name: Build and push Generator
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./docker/generator.Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
              ghcr.io/hackmac89/ascii_art_suite:ascii-art-generator-${{ env.SHORT_SHA }}
              ghcr.io/hackmac89/ascii_art_suite/ascii-art-generator:latest
            labels: org.opencontainers.image.source="https://github.com/hackmac89/ascii_art_suite/ascii-art-generator"
        - name: Build and push Viewer
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./docker/viewer.Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
              ghcr.io/hackmac89/ascii_art_suite:ascii-art-viewer-${{ env.SHORT_SHA }}
              ghcr.io/hackmac89/ascii_art_suite/ascii-art-viewer:latest
            labels: org.opencontainers.image.source="https://github.com/hackmac89/ascii_art_suite/ascii-art-viewer"
    tag:
        name: Tag and Release ASCII Art Suite
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: build
        steps:
        # initial checkout of this repo
        - uses: actions/checkout@v4
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
            WITH_V: false
    build-release-artifacts:
        name: Build Release Artifacts
        runs-on: ${{ matrix.os }}  # Use dynamic runner based on OS
        needs: [build,tag]
        strategy:
          matrix:
            #os: [windows-latest, ubuntu-latest, macos-latest]
            os: [ubuntu-latest, macos-latest]
            arch: [amd64, arm64]
            include:
              - os: ubuntu-latest
                EXT: ""
              - os: macos-latest
                EXT: ""
              #- os: windows-latest
              #  EXT: ".exe"
        steps:
        # initial checkout of this repo
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # get tags for usage in the "softprops/action-gh-release" action
        - name: Sparse Checkout für Submodule
          run: |
            git submodule init
            git submodule update --depth 1 --checkout --remote
            cd generator/external/stb
            git sparse-checkout init --cone
            git sparse-checkout set --skip-checks stb_image.h
            git pull origin master
        - name: Install Dependencies (Linux)
          if: matrix.os == 'linux'
          run: sudo apt update && sudo apt install -y build-essential
        - name: Compile Generator
          run: |
            mkdir -p dist
            gcc -Wall -pedantic -std=c99 -O2 -v -o dist/aart_generator-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.EXT }} generator/*.c -lm
        - name: Compile Viewer
          run: |
            mkdir -p dist
            gcc -Wall -pedantic -std=c99 -O2 -v -o dist/aart_viewer-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.EXT }} viewer/*.c -lm
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: binaries
            path: dist/*
    create_release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: build-release-artifacts
        steps:
        # initial checkout of this repo
        - uses: actions/checkout@v4
        - name: Get previously created tag
          id: get_tag
          run: echo "new_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        - name: Download Artifacts
          uses: actions/download-artifact@v3
          with:
            name: binaries
        - name: Upload Binaries to Release
          uses: softprops/action-gh-release@v2
          #if: startsWith(github.ref, 'refs/tags/')
          with:
            files: dist/*
            name:  ${{ steps.get_tag.outputs.new_tag }}
            tag_name: ${{ steps.get_tag.outputs.new_tag }}
            token: ${{ secrets.AART_ASSET_RELEASE_TOKEN }}
